spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/v7_backend
    username: backend
    password: backend
  sql:
    init:
      mode: always
      data-locations:
        - 'classpath:db/seeds/user.sql'

