spring:
  sql:
    init:
      mode: always
      data-locations:
        - 'classpath:db/seeds/user.sql'
  jooq:
    sql-dialect: mariadb
  datasource:
    driverClassName: org.mariadb.jdbc.Driver

v7:
  test:
    test: deep

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "health"