v7:
  test:
    test: deep


springdoc:
  api-docs:
    path: "/openapi/v3/api-docs"
  swagger-ui:
    url: "../openapi/v3/api-docs" # url is relative to /swagger-ui/index.html so it also works with the /api prefix

