spring:
  sql:
    init:
      mode: always
  jooq:
    sql-dialect: mariadb
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/backend
    username: backend
    password: backend
